### ISSUE TITLE
Plans to Support GitHub Actions?

### ISSUE THREAD

**Issue by christophwille** [BMuuN/vsts-assemblyinfo-task#135]
We (https://github.com/icsharpcode/ that is) are using your task in some of our Azure DevOps pipelines. However, we do intend to move to GH Actions & Packages at some point in the future. Are there any plans on your end to also support GH Actions?

**Comment by BMuuN** [comment]
Yes this is something I want to look into.  I can't give a timeframe on when it will happen but it's definitely on the cards 👍

**Comment by BMuuN** [comment]
This was a feature I was hoping to have completed by now but other commitments mean I don't have enough time.  Closing this issue but I'm hopeful I'll revisit this in the future.

**Comment by julianxhokaxhiu** [comment]
May I ask if you're still having an intention to support it? So far your repo seems to be the most mature on this direction. I was a really happy user so far on Azure DevOps, but recently I had to migrate to Github Actions. Would be awesome if you could port this project also over there, there's currently no other action on par with your own.

Additionally, since you're already using Node, shouldn't be too hard to port, probably you only need to craft the `action.yml` the rest should be good to go.

Thank you in advance!

**Comment by christophwille** [comment]
We have switched to https://github.com/roryprimrose/set-vs-sdk-project-version, eg https://github.com/icsharpcode/WpfDesigner/blob/master/.github/workflows/dotnet.yml
