### ISSUE TITLE
Keep parts of the original version?

### ISSUE THREAD

**Issue by hisbluness** [BMuuN/vsts-assemblyinfo-task#47]
Hey,

thanks for this extension, it works fine but I have another request/idea:

Would it be possible to maintain parts of the original version in the Assembly*.cs? For instance, the major.minor part and have the rest e.g. automated/incremented:

[major].[minor].$Build.BuildId

Thanks for any feedback!
blu

**Comment by wiz0u** [comment]
Yes, this! Please!

**Comment by TripleEmcoder** [comment]
Since in semantic versioning the way a version number is incremented needs to closely match the type of API changes that occur, it makes a lot of sense to update major.minor(.revision) in source, and only leave the patch and revision number to the pipeline task for unique values. Is there a way to accomplish this with the current version of the task, i.e. only update one segment of a version attribute and leave all other as-is?

**Comment by BMuuN** [comment]
Unfortunately the current version of the task doesn't support this feature.

There are several features I'd like to implement (this one included) however I just don't have the time these days.

**Comment by TripleEmcoder** [comment]
@BMuuN thanks for replying and all your work on this project.

For anyone coming here with the same requirement we managed to work around the lack of this feature by skipping the task altogether and simply using <VersionPrefix> in our project files and --version-suffix $(whatever) as a build parameter, see more information here: https://andrewlock.net/version-vs-versionsuffix-vs-packageversion-what-do-they-all-mean/

**Comment by BMuuN** [comment]
Added this functionality to `v3.1` and it will be released shortly.  I'll comment below once it has been released.

I've updated the [wiki](https://github.com/BMuuN/vsts-assemblyinfo-task/wiki/Versioning#keep-parts-of-original-version) to describe how this functionality is intended to work.

**Comment by BMuuN** [comment]
Closing as this has been implemented, just waiting a release.
